// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nexus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260205200446_AddPipelinesAndDeploymentExternalId")]
    partial class AddPipelinesAndDeploymentExternalId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nexus.Domain.Entities.AiSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AiType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ai_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("ToolName")
                        .HasColumnType("text")
                        .HasColumnName("tool_name");

                    b.HasKey("Id")
                        .HasName("pk_ai_signals");

                    b.HasIndex("PullRequestId")
                        .HasDatabaseName("ix_ai_signals_pull_request_id");

                    b.ToTable("ai_signals");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_branches");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_branches_repository_id");

                    b.ToTable("branches");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.BranchIssueLink", b =>
                {
                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid")
                        .HasColumnName("branch_id");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.HasKey("BranchId", "IssueId")
                        .HasName("pk_branch_issue_links");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_branch_issue_links_issue_id");

                    b.ToTable("branch_issue_links");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.CodeChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommitId")
                        .HasColumnType("uuid")
                        .HasColumnName("commit_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<bool>("IsRefactor")
                        .HasColumnType("boolean")
                        .HasColumnName("is_refactor");

                    b.Property<bool>("IsRework")
                        .HasColumnType("boolean")
                        .HasColumnName("is_rework");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer")
                        .HasColumnName("lines_added");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer")
                        .HasColumnName("lines_deleted");

                    b.Property<Guid?>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.HasKey("Id")
                        .HasName("pk_code_changes");

                    b.HasIndex("CommitId")
                        .HasDatabaseName("ix_code_changes_commit_id");

                    b.HasIndex("PullRequestId")
                        .HasDatabaseName("ix_code_changes_pull_request_id");

                    b.ToTable("code_changes");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Commit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorEmail")
                        .HasColumnType("text")
                        .HasColumnName("author_email");

                    b.Property<string>("AuthorName")
                        .HasColumnType("text")
                        .HasColumnName("author_name");

                    b.Property<DateTime>("AuthoredDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authored_date");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("committed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text")
                        .HasColumnName("web_url");

                    b.HasKey("Id")
                        .HasName("pk_commits");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_commits_repository_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_commits_user_id");

                    b.ToTable("commits");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CommitId")
                        .HasColumnType("uuid")
                        .HasColumnName("commit_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TriggerActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("trigger_actor_id");

                    b.HasKey("Id")
                        .HasName("pk_deployments");

                    b.HasIndex("CommitId")
                        .HasDatabaseName("ix_deployments_commit_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_deployments_service_id");

                    b.HasIndex("TriggerActorId")
                        .HasDatabaseName("ix_deployments_trigger_actor_id");

                    b.ToTable("deployments");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<Guid?>("RootCauseCommitId")
                        .HasColumnType("uuid")
                        .HasColumnName("root_cause_commit_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("RootCauseCommitId")
                        .HasDatabaseName("ix_incidents_root_cause_commit_id");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_incidents_service_id");

                    b.ToTable("incidents");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .HasColumnType("text")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_integrations");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_integrations_workspace_id");

                    b.ToTable("integrations");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<Guid?>("ParentIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_issue_id");

                    b.Property<string>("Priority")
                        .HasColumnType("text")
                        .HasColumnName("priority");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_issues_integration_id");

                    b.HasIndex("ParentIssueId")
                        .HasDatabaseName("ix_issues_parent_issue_id");

                    b.ToTable("issues");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueAssignee", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("IssueId", "UserId")
                        .HasName("pk_issue_assignees");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issue_assignees_user_id");

                    b.ToTable("issue_assignees");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueEstimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EstimateUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estimate_unit");

                    b.Property<double>("EstimateValue")
                        .HasColumnType("double precision")
                        .HasColumnName("estimate_value");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.HasKey("Id")
                        .HasName("pk_issue_estimates");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_estimates_issue_id");

                    b.ToTable("issue_estimates");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorToolAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_tool_account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousValue")
                        .HasColumnType("text")
                        .HasColumnName("previous_value");

                    b.HasKey("Id")
                        .HasName("pk_issue_events");

                    b.HasIndex("ActorToolAccountId")
                        .HasDatabaseName("ix_issue_events_actor_tool_account_id");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_issue_events_issue_id");

                    b.ToTable("issue_events");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueSprintLink", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid")
                        .HasColumnName("sprint_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("IssueId", "SprintId")
                        .HasName("pk_issue_sprint_links");

                    b.HasIndex("SprintId")
                        .HasDatabaseName("ix_issue_sprint_links_sprint_id");

                    b.ToTable("issue_sprint_links");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.MetricThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("metric_name");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("segment");

                    b.HasKey("Id")
                        .HasName("pk_metric_thresholds");

                    b.ToTable("metric_thresholds");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Pipeline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<int>("Iid")
                        .HasColumnType("integer")
                        .HasColumnName("iid");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebUrl")
                        .HasColumnType("text")
                        .HasColumnName("web_url");

                    b.HasKey("Id")
                        .HasName("pk_pipelines");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_pipelines_integration_id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_pipelines_repository_id");

                    b.ToTable("pipelines");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PullRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorToolAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_tool_account_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<int?>("CycleTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_time_minutes");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("FirstReviewAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_review_at");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ai_generated");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("merged_at");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer")
                        .HasColumnName("review_count");

                    b.Property<int>("SizeLines")
                        .HasColumnType("integer")
                        .HasColumnName("size_lines");

                    b.Property<string>("SourceBranch")
                        .HasColumnType("text")
                        .HasColumnName("source_branch");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("TargetBranch")
                        .HasColumnType("text")
                        .HasColumnName("target_branch");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_pull_requests");

                    b.HasIndex("AuthorToolAccountId")
                        .HasDatabaseName("ix_pull_requests_author_tool_account_id");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_pull_requests_integration_id");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_pull_requests_repository_id");

                    b.ToTable("pull_requests");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PullRequestReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorToolAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_tool_account_id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("PullRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("pull_request_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_pull_request_reviews");

                    b.HasIndex("AuthorToolAccountId")
                        .HasDatabaseName("ix_pull_request_reviews_author_tool_account_id");

                    b.HasIndex("PullRequestId")
                        .HasDatabaseName("ix_pull_request_reviews_pull_request_id");

                    b.ToTable("pull_request_reviews");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.RawEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_raw_events");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_raw_events_integration_id");

                    b.ToTable("raw_events");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_releases");

                    b.HasIndex("ServiceId")
                        .HasDatabaseName("ix_releases_service_id");

                    b.ToTable("releases");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DefaultBranch")
                        .HasColumnType("text")
                        .HasColumnName("default_branch");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_repositories");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_repositories_integration_id");

                    b.ToTable("repositories");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Lifecycle")
                        .HasColumnType("text")
                        .HasColumnName("lifecycle");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_team_id");

                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_services");

                    b.HasIndex("OwnerTeamId")
                        .HasDatabaseName("ix_services_owner_team_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_services_workspace_id");

                    b.ToTable("services");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ServiceRepository", b =>
                {
                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("repository_id");

                    b.Property<string>("PathFilter")
                        .HasColumnType("text")
                        .HasColumnName("path_filter");

                    b.HasKey("ServiceId", "RepositoryId")
                        .HasName("pk_service_repositories");

                    b.HasIndex("RepositoryId")
                        .HasDatabaseName("ix_service_repositories_repository_id");

                    b.ToTable("service_repositories");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_sprints");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_sprints_integration_id");

                    b.ToTable("sprints");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_team_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ParentTeamId")
                        .HasDatabaseName("ix_teams_parent_team_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_teams_workspace_id");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("TeamId", "UserId")
                        .HasName("pk_team_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_team_members_user_id");

                    b.ToTable("team_members");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ToolAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("ExternalEmail")
                        .HasColumnType("text")
                        .HasColumnName("external_email");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("ExternalMetadata")
                        .HasColumnType("text")
                        .HasColumnName("external_metadata");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("integration_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_tool_accounts");

                    b.HasIndex("IntegrationId")
                        .HasDatabaseName("ix_tool_accounts_integration_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tool_accounts_user_id");

                    b.ToTable("tool_accounts");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.UserAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_availabilities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_availabilities_user_id");

                    b.ToTable("user_availabilities");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.ToTable("workspaces");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.AiSignal", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.PullRequest", "PullRequest")
                        .WithMany("AiSignals")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_signals_pull_requests_pull_request_id");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Repository", "Repository")
                        .WithMany("Branches")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branches_repositories_repository_id");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.BranchIssueLink", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_issue_links_branches_branch_id");

                    b.HasOne("Nexus.Domain.Entities.Issue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_branch_issue_links_issues_issue_id");

                    b.Navigation("Branch");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.CodeChange", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Commit", "Commit")
                        .WithMany("CodeChanges")
                        .HasForeignKey("CommitId")
                        .HasConstraintName("fk_code_changes_commits_commit_id");

                    b.HasOne("Nexus.Domain.Entities.PullRequest", "PullRequest")
                        .WithMany()
                        .HasForeignKey("PullRequestId")
                        .HasConstraintName("fk_code_changes_pull_requests_pull_request_id");

                    b.Navigation("Commit");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Commit", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_commits_repositories_repository_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_commits_users_user_id");

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Deployment", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Commit", "Commit")
                        .WithMany()
                        .HasForeignKey("CommitId")
                        .HasConstraintName("fk_deployments_commits_commit_id");

                    b.HasOne("Nexus.Domain.Entities.Service", "Service")
                        .WithMany("Deployments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_deployments_services_service_id");

                    b.HasOne("Nexus.Domain.Entities.User", "TriggerActor")
                        .WithMany()
                        .HasForeignKey("TriggerActorId")
                        .HasConstraintName("fk_deployments_users_trigger_actor_id");

                    b.Navigation("Commit");

                    b.Navigation("Service");

                    b.Navigation("TriggerActor");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Incident", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Commit", "RootCauseCommit")
                        .WithMany()
                        .HasForeignKey("RootCauseCommitId")
                        .HasConstraintName("fk_incidents_commits_root_cause_commit_id");

                    b.HasOne("Nexus.Domain.Entities.Service", "Service")
                        .WithMany("Incidents")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incidents_services_service_id");

                    b.Navigation("RootCauseCommit");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Integration", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrations_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Issue", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_integrations_integration_id");

                    b.HasOne("Nexus.Domain.Entities.Issue", "ParentIssue")
                        .WithMany()
                        .HasForeignKey("ParentIssueId")
                        .HasConstraintName("fk_issues_issues_parent_issue_id");

                    b.Navigation("Integration");

                    b.Navigation("ParentIssue");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueAssignee", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Issue", "Issue")
                        .WithMany("Assignees")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_assignees_issues_issue_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_assignees_users_user_id");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueEstimate", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Issue", "Issue")
                        .WithMany("Estimates")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_estimates_issues_issue_id");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueEvent", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.ToolAccount", "ActorToolAccount")
                        .WithMany()
                        .HasForeignKey("ActorToolAccountId")
                        .HasConstraintName("fk_issue_events_tool_accounts_actor_tool_account_id");

                    b.HasOne("Nexus.Domain.Entities.Issue", "Issue")
                        .WithMany("Events")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_events_issues_issue_id");

                    b.Navigation("ActorToolAccount");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.IssueSprintLink", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Issue", "Issue")
                        .WithMany("SprintLinks")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_sprint_links_issues_issue_id");

                    b.HasOne("Nexus.Domain.Entities.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_sprint_links_sprints_sprint_id");

                    b.Navigation("Issue");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Pipeline", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pipelines_integrations_integration_id");

                    b.HasOne("Nexus.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pipelines_repositories_repository_id");

                    b.Navigation("Integration");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PullRequest", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.ToolAccount", "AuthorToolAccount")
                        .WithMany()
                        .HasForeignKey("AuthorToolAccountId")
                        .HasConstraintName("fk_pull_requests_tool_accounts_author_tool_account_id");

                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pull_requests_integrations_integration_id");

                    b.HasOne("Nexus.Domain.Entities.Repository", "Repository")
                        .WithMany("PullRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pull_requests_repositories_repository_id");

                    b.Navigation("AuthorToolAccount");

                    b.Navigation("Integration");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PullRequestReview", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.ToolAccount", "AuthorToolAccount")
                        .WithMany()
                        .HasForeignKey("AuthorToolAccountId")
                        .HasConstraintName("fk_pull_request_reviews_tool_accounts_author_tool_account_id");

                    b.HasOne("Nexus.Domain.Entities.PullRequest", "PullRequest")
                        .WithMany("Reviews")
                        .HasForeignKey("PullRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pull_request_reviews_pull_requests_pull_request_id");

                    b.Navigation("AuthorToolAccount");

                    b.Navigation("PullRequest");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.RawEvent", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_raw_events_integrations_integration_id");

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Release", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_releases_services_service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Repository", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repositories_integrations_integration_id");

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Service", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Team", "OwnerTeam")
                        .WithMany("OwnedServices")
                        .HasForeignKey("OwnerTeamId")
                        .HasConstraintName("fk_services_teams_owner_team_id");

                    b.HasOne("Nexus.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_services_workspaces_workspace_id");

                    b.Navigation("OwnerTeam");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ServiceRepository", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_repositories_repositories_repository_id");

                    b.HasOne("Nexus.Domain.Entities.Service", "Service")
                        .WithMany("ServiceRepositories")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_repositories_services_service_id");

                    b.Navigation("Repository");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Sprint", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprints_integrations_integration_id");

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Team", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Team", "ParentTeam")
                        .WithMany("SubTeams")
                        .HasForeignKey("ParentTeamId")
                        .HasConstraintName("fk_teams_teams_parent_team_id");

                    b.HasOne("Nexus.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_workspaces_workspace_id");

                    b.Navigation("ParentTeam");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_users_user_id");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.ToolAccount", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.Integration", "Integration")
                        .WithMany()
                        .HasForeignKey("IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tool_accounts_integrations_integration_id");

                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tool_accounts_users_user_id");

                    b.Navigation("Integration");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.UserAvailability", b =>
                {
                    b.HasOne("Nexus.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_availabilities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Commit", b =>
                {
                    b.Navigation("CodeChanges");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Assignees");

                    b.Navigation("Estimates");

                    b.Navigation("Events");

                    b.Navigation("SprintLinks");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.PullRequest", b =>
                {
                    b.Navigation("AiSignals");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Repository", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Commits");

                    b.Navigation("PullRequests");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Service", b =>
                {
                    b.Navigation("Deployments");

                    b.Navigation("Incidents");

                    b.Navigation("ServiceRepositories");
                });

            modelBuilder.Entity("Nexus.Domain.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("OwnedServices");

                    b.Navigation("SubTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
